import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import{AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';
import Image  from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Preet Yadav Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
       <section className=' min-h-screen'>
      <nav className='py-10 mb-12 flex justify-between'>
        <h1 className='text-xl font-burtons dark:text-gray-300'>Developed by Preet</h1>
        <ul className='flex items-center'>
          <li>
            <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-xl dark:text-gray-300'/>
          </li>
          <li><a className=' bg-gradient-to-b from-purple-600 to-rose-600 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
        </ul>
      </nav>
      <div className='text-center p-10'>
        <h2 className='text-5xl py-2 text-emrald-600 font-medium md:text-6xl  dark:text-gray-300'>Preet Yadav</h2>
        <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-300'>Developer and designer.</h3>
        <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-100'>Freelancer providing services for programming and designing content needs. Join me down below and let's get cracking!</p>
      </div>
      <div className='text-5xl flex justify-center gap-16 py-3 '>
  <AiFillTwitterCircle  className='text-blue-500' />
<AiFillLinkedin className='text-blue-800'/>
<AiFillYoutube className='text-red-600'/>
      </div>
    <div className='relative mx-auto bg-gradient-to-t from-purple-500 to-rose-600 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
<Image src={deved} layout="fill" objectFit='cover'/>
    </div>
       </section>

      <section>
        <div>
          <h3 className='text-3xl py-1 dark:text-indigo-400'>Skills & Services</h3>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>Since the beginning of my journey as a Freelancer web developer, I've done remote work for
          <span className='text-emrald-500'>agencies</span>consulted for <span className='text-emrald-500'>startups</span> and collabrated with talented people to create digital products for both business and consumer use.</p>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400'>
            I offer from a wide range of services, including programming and teaching.
          </p>
        </div>
        <div className='lg:flex gap-10'>
         <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gradient-to-b from-fuchsia-600 to-rose-500'>
         <Image src={design} width={100} height={100} />
         <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
         <p className='py-2'>
          Creating elegant desings suited for your needs following core design theory.
         </p>
         <h4 className='py-4 text-emerald-600 dark:text-indigo-200'>Design tools I use</h4>
         <p className='text-grey-800 py-1'>Photoshop</p>
         <p className='text-grey-800 py-1'>Illustrator</p>
         <p className='text-grey-800 py-1'>Figma</p>
          </div>

          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gradient-to-b from-rose-500 to-pink-500'>
         <Image src={code} width={100} height={100} />
         <h3 className='text-lg font-medium pt-8 pb-2'>Codes</h3>
         <p className='py-2'>
          Capapble of making projects in various Programming Languages.
         </p>
         <h4 className='py-4 text-emerald-600 dark:text-indigo-200'>Programming Languages</h4>
         <p className='text-grey-800 py-1'>Java</p>
         <p className='text-grey-800 py-1'>HTML</p>
         <p className='text-grey-800 py-1'>CSS</p>
          </div>

          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gradient-to-b from-pink-500 to-purple-300'>
         <Image src={consulting} width={100} height={100} />
         <h3 className='text-lg font-medium pt-8 pb-2'>Consulting</h3>
         <p className='py-2'>
          Support and Guidence provided to enhance understanding.
         </p>
         <h4 className='py-4 text-emerald-600 dark:text-indigo-200'>Services I provide</h4>
         <p className='text-grey-800 py-1'>Seminars</p>
         <p className='text-grey-800 py-1'>Lectures</p>
         <p className='text-grey-800 py-1'>Online Meetings</p>
          </div>

          
        </div>
      </section>
<section>
  <div>
    <h3 className='text-3xl py-1 dark:text-gray-300'>Portfolio</h3>
    <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-500'>Since the beginning of my journey as a Freelancer web developer, I've done remote work for
          <span className='text-emrald-500'>agencies</span>consulted for <span className='text-emrald-500'>startups</span> and collabrated with talented people to create digital products for both business and consumer use.</p>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-500'>
            I offer from a wide range of services, including programming and teaching.
          </p>
  </div>
     <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
      <div className='basis-1/3 flex-1'>
        <Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
      </div>
      <div className='basis-1/3 flex-1'>
        <Image src={web2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
      </div>
      <div className='basis-1/3 flex-1'>
        <Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
      </div>
      <div className='basis-1/3 flex-1'>
        <Image src={web4} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
      </div>
      <div className='basis-1/3 flex-1'>
        <Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
      </div>
      <div className='basis-1/3 flex-1'>
        <Image src={web6} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
      </div>
     </div>
</section>
      </main>
    </div>
  );
}
